export const STORAGE_KEY = {
  SETTINGS: "settings",
};

export const MESSAGE = {
  TAB_ACTIVE: "TAB_ACTIVE",
  TAB_INACTIVE: "TAB_INACTIVE",
  TAB_INITIAL_ACTIVE: "TAB_INITIAL_ACTIVE",
  TAB_INITIAL_INACTIVE: "TAB_INITIAL_INACTIVE",
  TAB_VIDEO_CHANGED: "TAB_VIDEO_CHANGED",
  COMMENTS: "COMMENTS",
};

export const REQUEST = {
  GET_COMMENTS: "GET_COMMENTS",
  PUT_ANALYTICS: "PUT_ANALYTICS",
};

export const EVENT = {
  CHUNK: "CHUNK",
  RESET: "RESET",
  FETCHING: "FETCHING",
  FETCHING_FINISHED: "FETCHING_FINISHED",
  VIDEO_HAS_CHANGED: "VIDEO_HAS_CHANGED",
};

export const ID = {
  BUTTON: "comments-button",
  BAR: "comments-bar",
};
